In [ ]:
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables

In [19]:
#Ans1
Yes, there is difference between variable list and array list.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
print(type(list_))
list_1 = np.array([['1'], ['2'], ['3'], ['4'], ['5']])
print(type(list_1))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [12]:
#Ans2
print("Data Types in Variable List")
list = ["Alpha", 34, 32.43, "Physics Wallah"]
for i in list:
    print(type(i))

array_list = ([[23], [24.23], ["Sure"]])
print("Data Types in Array List")
for i in array_list:
    print(type(i))

Data Types in Variable List
<class 'str'>
<class 'int'>
<class 'float'>
<class 'str'>
Data Types in Array List
<class 'list'>
<class 'list'>
<class 'list'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [30]:
#Ans3
import numpy as np
array_list = np.array(object = list_, dtype = int)
print("Data Type in Array List: ", type(array_list))
print("Data Type in Variable List: ",type(list_))

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
print(num_array.dtype)

for i in num_list:
    print(type(i))
for j in num_array:
    print(j.dtype)

Data Type in Array List:  <class 'numpy.ndarray'>
Data Type in Variable List:  <class 'list'>
int32
<class 'list'>
<class 'list'>
int32
int32


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [34]:
#Ans4
#i) Shape
print(num_array.shape)

#ii) Size
print(num_array.size)

(2, 3)
6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [46]:
#Ans5
arr = np.zeros((3,3))
print(arr)
print("Size of Array = ",arr.size)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Size of Array =  9


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [50]:
#Ans6
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])